// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAmokmqYseqMFUy-_F5C0z3gcZ35oEZ8I',
    appId: '1:878493929047:android:ea02ed9b31f565a75c1d12',
    messagingSenderId: '878493929047',
    projectId: 'mathdictionary-f4765',
    storageBucket: 'mathdictionary-f4765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkiqRWNq3ZHWS-Do8XN-eIzYv1jaO9CoQ',
    appId: '1:878493929047:ios:7a5dc2c7e26d6d995c1d12',
    messagingSenderId: '878493929047',
    projectId: 'mathdictionary-f4765',
    storageBucket: 'mathdictionary-f4765.appspot.com',
    iosBundleId: 'com.example.mathDictionary2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkiqRWNq3ZHWS-Do8XN-eIzYv1jaO9CoQ',
    appId: '1:878493929047:ios:7a5dc2c7e26d6d995c1d12',
    messagingSenderId: '878493929047',
    projectId: 'mathdictionary-f4765',
    storageBucket: 'mathdictionary-f4765.appspot.com',
    iosBundleId: 'com.example.mathDictionary2',
  );
}
